#!/bin/sh

# Requires ETCD URL as $1 - typically http://172.17.42.1:4001/

etcdctl mkdir /clusterdemo
etcdctl mkdir /clusterdemo/loadbalancer
etcdctl mkdir /clusterdemo/webserver
etcdctl mkdir /clusterdemo/dbserver
